version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: inventory-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  inventory-network:
    driver: bridge

volumes:
  postgres_data:
